### ISSUE TITLE
Support/instructions for Pipx install

### ISSUE THREAD

**Issue by distefam** [haskellcamargo/sclack#128]
I use [pipx](https://pipxproject.github.io/pipx/) to manage Python executables on my system and would like to use it to install Sclack. I tried running the following command in Pipx:
`pipx install --include-deps --spec git+https://github.com/haskellcamargo/sclack.git sclack` which seemed to have worked, however, it installed Sclack as a binary in my path `~/.local/bin` named `app.py` rather than `sclack` and when I attempt to run `app.py` (which is exposed on my path) I get the following errors:

```
Traceback (most recent call last):
  File "/home/michael/.local/bin/app.py", line 14, in <module>
    from sclack.components import Attachment, Channel, ChannelHeader, ChatBox, Dm
  File "/home/michael/.local/pipx/venvs/sclack/lib/python3.7/site-packages/sclack/components.py", line 11, in <module>
    from .markdown import MarkdownText
  File "/home/michael/.local/pipx/venvs/sclack/lib/python3.7/site-packages/sclack/markdown.py", line 3, in <module>
    from .store import Store
  File "/home/michael/.local/pipx/venvs/sclack/lib/python3.7/site-packages/sclack/store.py", line 1, in <module>
    from slackclient import SlackClient
ModuleNotFoundError: No module named 'slackclient'
```

**Comment by FIGBERT** [comment]
Seems like this would be fixed by #115 – what's the status on that?
