### ISSUE TITLE
Sclack won't work at bootstrap

### ISSUE THREAD

**Issue by Lakshamana** [haskellcamargo/sclack#135]
Hello, I'm trying to run Sclack on a Python 3.x env and it just breaks on app init
![image](https://user-images.githubusercontent.com/29443505/91208733-07bbce00-e6e1-11ea-8208-dbe0a6e05037.png)

Software setup:
Python
```
▶ python3 -V
Python 3.8.5
```
Pip
```
▶ pip3 -V
pip 20.1.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
```
OS
```
▶ uname -a
Linux <user> 5.7.15-1-MANJARO #1 SMP PREEMPT Tue Aug 11 15:00:37 UTC 2020 x86_64 GNU/Linux
```
Some stack tracing:
```Traceback (most recent call last):
  File "./app.py", line 967, in <module>
    app.start()
  File "./app.py", line 103, in start
    self.urwid_loop.run()
  File "/home/arjuna/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/arjuna/.local/lib/python3.8/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "./app.py", line 38, in run
    self._loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
```

I've already tried using `sudo`, but it doesn't work as well. Do you need something else?

**Comment by Lakshamana** [comment]
I closed but, hold up! Maybe `mpim.list` doesn't exist anymore. Maybe you shoud use another API endpoint. Notice I don't know at all about Slack API, so I must be speaking some sillyness... Anyway, that's my analysis since I couldn't add `mpim.list` to user scopes

**Comment by tmferretti** [comment]
I also am running into this issue

**Comment by tmferretti** [comment]
```sclack git:(master) ✗ python3 --version
Python 3.7.3

sclack git:(master) ✗ pip3 -V
pip 19.0.3 from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)

➜  sclack git:(master) ✗ uname -a
Darwin Thomass-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64```

**Comment by schellj** [comment]
I'm also running into the exact same issue.

```
[~]$ python3 -V
Python 3.8.5
[~]$ pip3 -V
pip 20.1.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
[~]$ uname -a
Darwin Justins-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64 i386 MacBookPro14,1 Darwin
```

**Comment by schellj** [comment]
FYI, I created a PR to fix this issue (#136).

**Comment by JPTIZ** [comment]
For me, Sclack still won't work. There's still probably references to an old slack API (see images below). Everytime I run, the error changes, but it is always related to those dictionary keys.

![image](https://user-images.githubusercontent.com/11988816/97619424-f6ec4900-19fe-11eb-9323-6f39b37b87ab.png)
![image](https://user-images.githubusercontent.com/11988816/97619507-0f5c6380-19ff-11eb-93d4-580c4ed30727.png)

**Comment by DrGrognon** [comment]
I got the exact same as @JPTIZ   (except from background dog :stuck_out_tongue_closed_eyes: )
Fresh install from repo today.
```
$ pip3 -V
pip 20.3.1 from /home/bgonon/usr/vendors/pyenv/versions/3.6.9/lib/python3.6/site-packages/pip (python 3.6)
$ python3 -V
Python 3.6.9
$ uname -a
Linux  5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Hope you can fix, screenshots look awesome :cry:

**Comment by duynguyenhoang** [comment]
@JPTIZ  @DrGrognon can you please pull master and check it again?

**Comment by JPTIZ** [comment]
> @JPTIZ @DrGrognon can you please pull master and check it again?

Just tried (`cd <my sclack clone>`, `git checkout master`, `git pull`) and still got this:

![image](https://user-images.githubusercontent.com/11988816/117397436-856fe480-aed2-11eb-9b4a-3a6b00b0048d.png)

Just to confirm, the git log output:

```console
$ git log --oneline
c44ddbc (HEAD -> master, origin/master, origin/HEAD) Merge pull request #139 from haskellcamargo/dependabot/pip/requests-2.20.0                                                                                                                
c7a8c02 Merge pull request #143 from GSGBen/master                                                                                                                                                                                             
1b8e590 Fix error on load
```

**Comment by JPTIZ** [comment]
For more information:

```console
$ pip freeze
asyncio==3.4.3
certifi==2020.12.5
chardet==4.0.0
idna==2.10
pyperclip==1.6.2
requests==2.25.1
six==1.15.0
slackclient==1.2.1
urllib3==1.26.2
urwid==2.0.1
urwid-readline==0.13
websocket-client==0.47.0
```
