### ISSUE TITLE
Error on startup in mount_sidebar

### ISSUE THREAD

**Issue by roveo** [haskellcamargo/sclack#21]
Here's the error:

```
Task exception was never retrieved
future: <Task finished coro=<App.component_did_mount() done, defined at app.py:97> exception=KeyError('groups',)>
Traceback (most recent call last):
  File "app.py", line 100, in component_did_mount
    yield from self.mount_sidebar(executor)
  File "app.py", line 109, in mount_sidebar
    loop.run_in_executor(executor, self.store.load_users)
  File "/Users/roveo/.pyenv/versions/3.6.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/roveo/sclack/sclack/store.py", line 99, in load_groups
    self.state.groups = self.slack.api_call('mpim.list')['groups']
KeyError: 'groups'
```

**Comment by haskellcamargo** [comment]
It seems like the Slack API has denied the request. This happens often when the same endpoint is requested too many times (Slack API has rating limits). I'll be working on a retry-attempt for requests to handle this kind of issue without breaking the things. Thanks!

**Comment by MarcosEich** [comment]
I am also getting an error on startup, maybe it is related.

```
Traceback (most recent call last):
  File "./app.py", line 560, in <module>
    app.start()
  File "./app.py", line 62, in start
    self.urwid_loop.run()
  File "/usr/local/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "./app.py", line 28, in run
    self._loop.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 523, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1722, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
```

**Comment by niltonvasques** [comment]
Same for me but with a different message:

![image](https://user-images.githubusercontent.com/2291529/43936666-f2b7ae50-9c2f-11e8-95d6-d97439000266.png)

**Comment by behconsci** [comment]
slack has different api now, they say, we should generate the token in workspace apps. I created their new app and i dont know what token I should use. there are many different ones

**Comment by behconsci** [comment]
for me also not working. same message.

**Comment by behconsci** [comment]
I will try to create better messages in a new pr

**Comment by behconsci** [comment]
ok it says, we need to give these scopes: 

![image](https://user-images.githubusercontent.com/10358323/43968860-a587ad12-9cc8-11e8-891b-5612a50f4a5a.png)

**Comment by behconsci** [comment]
I will make a PR for this with better error messages

**Comment by coryshaw1** [comment]
Also having issues on startup:

```
'channels'
File "./app.py", line 126, in component_did_mount
 yield from self.mount_sidebar(executor)
File "./app.py", line 135, in mount_sidebar
loop.run_in_executor(executor, self.store.load_users)
File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/Users/coryshaw/Documents/Code/sclack/sclack/store.py", line 86, in load_channels)['channels']
```

**Comment by coryshaw1** [comment]
Was able to output the response from the Slack API:

`{'ok': False, 'error': 'not_allowed_token_type', ...}`

I'm using tokens generated here: https://api.slack.com/custom-integrations/legacy-tokens

And my .sclack file looks like:

```js
{
    "workspaces": {
        "default": "xoxs-xxxx-xxxx-xxxx",
        "another": "xoxs-xxxx-xxxx-xxxx"
    }
}
```

Do some Slack workspaces have the ability to disable legacy tokens?

**Comment by behconsci** [comment]
you need to create apps then you get the tokens
